/* Merge + demographic frequencies from Final_Bonanno.sas.
   Recomputes age (SURGERIES2), merges surgeries with smoking history by PT_ID
   into COMPLETE, keeps the first record per patient (EVENT1), then produces the
   RACE, RACE*SEX and RACE*HOSMKG frequency tables.
   Reads SURGERIES + SMOKING provided by autoexec.sas. */
TITLE1 'PHST 620 Final Project Bonanno';

PROC SORT DATA=SURGERIES;
	BY PT_ID EVENT_DATE;
RUN;

DATA SURGERIES2;
	SET SURGERIES;
	BY PT_ID EVENT_DATE;
	RETAIN BASE_AGE BASE_DATE;

	IF FIRST.PT_ID THEN
		DO;
			BASE_AGE=AGE;
			BASE_DATE=EVENT_DATE;
		END;
	AGE=BASE_AGE +((EVENT_DATE-BASE_DATE)/365.25);
RUN;

PROC SORT DATA=SURGERIES2;
	BY PT_ID;
RUN;

PROC SORT DATA=SMOKING;
	BY PT_ID;
RUN;

DATA COMPLETE;
	MERGE SURGERIES2 (IN=A) SMOKING (IN=B);
	BY PT_ID;

	IF A AND B;
	KEEP PT_ID EVENT_DATE SEX AGE RACE OUTCOME CONDX HOSMKG;
RUN;

DATA EVENT1;
	SET COMPLETE;
	BY PT_ID;

	IF FIRST.PT_ID;
RUN;

PROC FREQ DATA=EVENT1;
	TABLES RACE /NOPERCENT NOCUM;
RUN;

PROC FREQ DATA=EVENT1;
	TABLES RACE*SEX /NOPERCENT NOROW NOCOL;
RUN;

PROC FREQ DATA=EVENT1;
	TABLES RACE*HOSMKG /NOPERCENT NOROW NOCOL;
RUN;
